version: '3'

services:

  app:
    build: .
    container_name: iniciando-nestjs-app-jwt
    entrypoint: ./.docker/entrypoint.sh
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app

  db:
    image: mysql:5.7
    container_name: iniciando-nestjs-db-jwt
    restart: always
    tty: true
    ports:
      - "33006:3306"
    volumes:
      - iniciando-nestjs-dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE= project_jwt_nest
      - MYSQL_ROOT_PASSWORD= root
      - TYPEORM_PASSWORD = feras5566

volumes:
  iniciando-nestjs-dbdata:
    external: true